### ISSUE TITLE
Can we take your project name for PyPI?

### ISSUE THREAD

**Issue by nilsnolde** [enricodvn/pyosrm#8]
Hi,

we're about to publish platform-independent wheels for OSRM Python bindings through a GSoC project: https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2023/Project_ideas. The problem is there's already lots of (unmaintained) projects which are often on PyPI and all have similar names. Now we're struggling to find a good name for the package.

We already support a few other packages in the same realm:
- https://github.com/gis-ops/pyvalhalla
- https://github.com/VROOM-Project/pyvroom

So `pyosrm` would fit in neatly :smile: Would you be OK to remove your project on PyPI so we can take over that name? We'd clearly state that this is the "new version" and refer back to your project.

**Comment by enricodvn** [comment]
Hello! 

Isn't there another option? I would gladly provide the name, given the wheels for the previous version be uploaded as 0.x and 1.x (it is coming!) versions to keep backwards compatibility.

**Comment by nilsnolde** [comment]
Ah alright, no worries then. I figured there wouldn’t be any updates as the last one is 3 years old.

I don’t mean to be telling people what to focus on, but I think the official bindings will be there to stay, and will provide all platforms (linux, mac, win). Just so you’re aware.

**Comment by enricodvn** [comment]
Sure thing! If you were less prepotent maybe.
